import ExploreFeed from '@/components/explore/ExploreFeed';
import shellStyles from '@/components/layout/AppShell.module.css';

export const metadata = {
  title: 'Explore',
  description: 'Browse viral video clips generated by creators on F33D.',
};

export default function ExplorePage() {
  return (
    <div className={`${shellStyles.pageSection} ${shellStyles.pageSectionWide}`}>
      <ExploreFeed />
    </div>
  );
}
